league_teams:
    path: /league/{id}/teams
    controller: App\Controller\LeagueController::leagueTeams
    methods: [GET]
    requirements:
        id: '\d+'
team_create:
    path: /league/{id}/team
    controller: App\Controller\LeagueController::teamCreate
    methods: [POST]
    requirements:
        id: '\d+'

team_edit:
    path: /team/{id}
    controller: App\Controller\LeagueController::teamEdit
    methods: [PATCH]
    requirements:
        id: '\d+'
league_delete:
    path: /league/{id}
    controller: App\Controller\LeagueController::leagueDelete
    methods: [DELETE]
    requirements:
        id: '\d+'